pluginManagement {
    repositories {
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
    }
}

plugins {
    id "dev.architectury.stonecutter" version "0.1.3"
}

rootProject.name = "ProjectE-Stonecutter"

stonecutter.active "1.10.2"

include "1.10.2"
project(":1.10.2").projectDir = file("versions/1.10.2")
