package moze_intel.projecte.integration.kubejs;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;
import moze_intel.projecte.PECore;
import moze_intel.projecte.config.MappingConfig;
import net.neoforged.fml.loading.FMLPaths;

public class RecipeConflictResolver {

	private static final List<String> conflicts = new ArrayList<>();

	public static void addConflict(String recipeId, String outputItem, String reason) {
		boolean active = MappingConfig.kubejsActive();
		String prefix = active ? "" : "// ";
		
		String scriptLine = String.format(
			"// Conflict Reason: %s\n%sServerEvents.recipes(event => {\n%s    event.remove({ id: '%s' });\n%s});\n",
			reason, prefix, prefix, recipeId != null ? recipeId : outputItem, prefix
		);
		
		if (recipeId == null) {
			// If we don't have an ID, we try to remove by output
			scriptLine = String.format(
				"// Conflict Reason: %s\n%sServerEvents.recipes(event => {\n%s    event.remove({ output: '%s' });\n%s});\n",
				reason, prefix, prefix, outputItem, prefix
			);
		}
		
		conflicts.add(scriptLine);
	}

	public static void flush() {
		if (conflicts.isEmpty()) {
			return;
		}

		Path kubejsDir = FMLPaths.GAMEDIR.get().resolve("kubejs").resolve("server_scripts");
		try {
			Files.createDirectories(kubejsDir);
			Path scriptFile = kubejsDir.resolve("e3_recipe_conflicts.js");
			
			StringBuilder sb = new StringBuilder();
			sb.append("// This file was automatically generated by e3 (ProjectE) to resolve EMC exploits and conflicts.\n");
			sb.append("// You can toggle active/inactive generation in the e3 server configs.\n\n");
			
			for (String conflict : conflicts) {
				sb.append(conflict).append("\n");
			}
			
			Files.write(scriptFile, sb.toString().getBytes(StandardCharsets.UTF_8), 
					StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
					
			PECore.LOGGER.info("Wrote {} KubeJS recipe conflict resolutions to {}", conflicts.size(), scriptFile.toString());
		} catch (IOException e) {
			PECore.LOGGER.error("Failed to write KubeJS recipe conflict script", e);
		}
		
		conflicts.clear();
	}
}
